"""
quotes used by bot
"""
quotes = [
    "I won’t say we have to win. I won’t put that pressure. But we can’t lose.",
    "It’s not important how we play. If you have a Ferrari and I have a small car, to beat you in a race I have to break your wheel or put sugar in your tank.",
    "You don’t have to love me. You don’t even have to like me, but you will respect me.",
    "Please don’t call me arrogant, but I’m European champion and I think I’m a special one.",
    "You have to work hard AND well. There are a lot of people who work hard but not well.",
    "Football is a game about feelings and intelligence.",
    "Dogs bark and the caravan goes by.",
    "I enjoy the work, I enjoy every minute of my professional life.",
    "But the most important part of everything is to be happy.",
    "Pressure? What pressure? Pressure is poor people in the world trying to feed their families. There is no pressure in football.",
    "I am José Mourinho and I don’t change. I arrive with all my qualities and my defects.",
    "I think Arsene Wenger is one of these people who is a voyeur. He likes to watch other people. There are some guys who, when they are at home, have a big telescope to see what happens in other families. He speaks, speaks, speaks about Chelsea.",
    "Young players are like melons. Only when you open and taste the melon are you 100% sure that the melon is good.",
    "You may as well put a cow in the middle of the pitch, walking. And then stop the game because there was a cow.",
    "Fear is not a word in my football dictionary.",
    "Some clubs are treated as devils, some are treated as angels. I don’t think we are so ugly that we should be seen as the devil and I don’t think Arsene Wenger and David Dein are so beautiful that they should be viewed as angels.",
    "At the moment, we cannot walk from the bed to the toilet without breaking a leg",
    "I want to push the young players on my team to have a proper haircut, not the Rastafarian or the others they have.",
    "A pundit is not honest if they cannot forget their colours or if they try to hide the truth from their audience. It’s not my fault if their managerial career was very poor.",
    "For me, the real age is not the age on your ID. That’s just a date when you were born.",
    "It’s like having a blanket that is too small for the bed. You pull the blanket up to keep your chest warm and your feet stick out. I cannot buy a bigger blanket because the supermarket is closed. But the blanket is made of cashmere",
    "We have top players and, sorry if I’m arrogant, we have a top manager.",
    "I have a problem, which is I’m getting better at everything related to my job since I started.",
    "If he is right and I am afraid of failure it is because I didn’t fail many times. Eight years without silverware, that’s failure. He’s a specialist in failure. If I do that in Chelsea, eight years, I leave and don’t come back.",
    "I have a lot of respect for Liverpool fans and what I did, the sign of silence – ‘shut your mouth’ – was not for them, it was for the English press.",
    "I would rather play with 10 men than wait for a player who is late for the bus.",
    "Look, I’m a coach, I’m not Harry Potter. He is magical, but in reality there is no magic. Magic is fiction and football is real.",
    "If they made a film of my life, I think they should get George Clooney to play me. He’s a fantastic actor and my wife thinks he would be ideal.",
    "Can Messi be suspended for acting? Barcelona is a cultural city with many great theatres and this boy has learned very well. He’s learned play-acting.",
    "We are a little horse. A horse that still needs milk and to learn how to jump.",
    "The style of how we play is very important. But it is omelettes and eggs. No eggs – no omelettes! It depends on the quality of the eggs. In the supermarket you have class one, two or class three eggs and some are more expensive than others and some give you better omelettes. So when the class one eggs are in Waitrose and you cannot go there, you have a problem.",
    "I think the lady needs to occupy her time, and if she takes care of her husband’s diet she will have less time to speak about me.",
    "You can say the linesman’s scored. It was a goal coming from the moon or from the Anfield Road stands.",
    "Every time I play Pep I end up with 10 men. It must be some sort of UEFA rule.",
    "Sometimes you see beautiful people with no brains. Sometimes you have ugly people who are intelligent, like scientists.",
    "If you want, you can make a silence very noisy.",
    "If I wanted to have an easy job…I would have stayed at Porto - beautiful blue chair, the Uefa Champions League trophy, God, and after God, me.",
    "I only talk about men, not of rude children.",
    "It is not a conspiracy, it is fact. I speak facts. If not, I need big glasses.",
    "When you enjoy what you do, you don’t lose your hair, and Guardiola is bald. He doesn’t enjoy football.",
    "Maybe the guy drank red wine or beer with breakfast instead of milk.",
    "My wife is in Portugal with the dog. The dog is with my wife so the city of London is safe, the big threat is away.",
    "The moral of the story is not to listen to those who tell you not to play the violin but stick to the tambourine",
    "There are lot of poets in football but they don’t win titles.",
    "I have nothing, nothing to say. Nothing, nothing to say. Nothing to say, I have nothing to say. Nothing to say, I am so sorry, I have nothing to say.",

]